site_name: GAICo Documentation
site_url: https://ai4society.github.io/projects/GenAIResultsComparator/
repo_url: https://github.com/ai4society/GenAIResultsComparator/
repo_name: ai4society/GenAIResultsComparator
edit_uri: tree/main/docs

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx
            show_root_heading: true # Shows the module/class name as a heading
            show_source: false # Set to true if you want to show source code
            show_category_heading: true # Shows category headings like "Classes", "Functions", etc.
            members_order: source # Order members as they appear in source
            heading_level: 2 # Adjust heading levels for API docs
            separate_signature: true # Shows signature on a new line from docstring
            show_signature_annotations: true # Ensures type hints are shown
            # merge_init_into_class: true # Merges __init__ docstring with class docstring
            # ignore_init_summary: true # Use if needed for summary lines
  - macros:
      module_name: project_macros
nav:
  - Home: index.md
  - Installation Guide: installation-guide.md
  - Resources: resources.md
  - FAQ: faq.md
  - News & Releases: news.md
  - Developer Guide: developer-guide.md
  - API Reference:
      - "Overview": api/metrics/index.md
      - "The Experiment Class": api/experiment.md
      - "Structured Metrics":
          - "Planning": api/metrics/planning.md
          - "Time Series": api/metrics/timeseries.md
      - "Textual Metrics":
          - "N-gram": api/metrics/ngram_metrics.md
          - "Semantic Similarity": api/metrics/semantic_similarity_metrics.md
          - "Text Similarity": api/metrics/text_similarity_metrics.md
      - "Multimedia Metrics":
          - "Image": api/metrics/image.md
          - "Audio": api/metrics/audio.md
      - "BaseMetric": api/metrics/base.md
      - "Utilities": api/utils.md
      - "Thresholds Module": api/thresholds_module.md
      - "Visualize Module": api/visualize_module.md
  - User Guide:
      - "Quick Start": user_guide/quickstart.md
      - "The Experiment Class": user_guide/experiment_class.md
      - "Using Metrics Directly": user_guide/direct_metrics.md
      - "Working with Thresholds": user_guide/thresholds.md
      - "Visualization": user_guide/visualization.md
  - License: license.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - github-callouts
